services:
  - type: web
    name: imdb-sentiment-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run imdb2025.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
